import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { RootState } from "../store/store";
import { getAlbumPhotoList } from "../../services/photoServices";

export interface AlbumPhotoState {
  albumPhotoList: [{
    albumId: number;
    id: number;
    title: string;
    url: string;
    thumbnailUrl: string;
  }?];
  status: "idle" | "loading" | "failed";
}

const initialState: AlbumPhotoState = {
  albumPhotoList: [],
  status: "idle",
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const getAlbumPhotos = createAsyncThunk(
  "getAlbumPhotos",
  async (id: string | undefined) => {
    if (id) {
      const response = await getAlbumPhotoList(id);
      // The value we return becomes the `fulfilled` action payload
      return response;
    }
    return false;
  }
);

export const albumPhotosSlice = createSlice({
  name: "albumPhotps",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getAlbumPhotos.pending, (state) => {
        state.status = "loading";
      })
      .addCase(getAlbumPhotos.fulfilled, (state, action) => {
        state.status = "idle";
        state.albumPhotoList = action.payload;
      })
      .addCase(getAlbumPhotos.rejected, (state) => {
        state.status = "failed";
      });
  },
});

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const albumPhotoListData = (state: RootState) =>
  state.albumPhoto.albumPhotoList;

export default albumPhotosSlice.reducer;
